### ISSUE TITLE
sysyf语法树构建

### ISSUE THREAD

**Issue by Elwin-zhao** [Komorebi660/SysYF-Compiler#1]
现在-emit-ast可以根据语法树复原代码，想问一下如果现在要单独展示打印构建的语法树，该怎么改呢

**Comment by Komorebi660** [comment]
你可以仿照 SyntaxTreePrinter 的实现，从 SyntaxTree::Visitor 继承一个新的类，然后复写每种节点的 visit() 方法 (在这里面实现对每一类节点的输出)，最后在main.cpp文件中添加相应的入口即可

**Comment by Elwin-zhao** [comment]
非常感谢，已经实现了。还有一个问题就是如果想打印符号表，可以直接用SyntaxTreeChecker里面的那个table吗

**Comment by Komorebi660** [comment]
可以的

**Comment by Elwin-zhao** [comment]
想问一下生成的中间代码和样例里附带的llvm中间代码有些不同是为什么呀
