### ISSUE TITLE
关于执行 make 后遇到的问题

### ISSUE THREAD

**Issue by lavinal712** [Komorebi660/SysYF-Compiler#2]
准备的工具都已经下载完成，当执行了 make 后，出现了两个 error：

![image](https://github.com/Komorebi660/SysYF-Compiler/assets/98888959/5b2a5e56-2f13-4dc8-86b8-c2bc8ce20101)

我想询问这是因为什么而出现错误，以及如何解决它。

**Comment by Komorebi660** [comment]
感觉可能是编译器版本太高了？要不降降级试试？

**Comment by lavinal712** [comment]
gcc 编译器版本是多少，我的是：gcc (Debian 13.1.0-6) 13.1.0

**Comment by Komorebi660** [comment]
我的版本是gcc 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2)

另外我更新了一下README，添加了我这边能跑通所用的各种依赖的版本信息。

**Comment by lavinal712** [comment]
之前使用 gcc 版本回退误操作删了所有的版本，重装了虚拟机系统后可以成功运行。（曲线救国？）

非常感谢！
